FALLBACK_ERROR_FORMAT: "json"
FORWARDED_FOR_HEADER: "X-Forwarded-For"
FORWARDED_SECRET: None
GRACEFUL_SHUTDOWN_TIMEOUT: 15.0
ACCESS_LOG: False
KEEP_ALIVE: True
KEEP_ALIVE_TIMEOUT: 15
LOGO: "Sanic Serve System"
REQUEST_MAX_SIZE: 100000000
REQUEST_TIMEOUT: 60
RESPONSE_TIMEOUT: 60
ENV: "PRO"

MYSQL:
  HOST: "192.168.10.187"
  PORT: 3306
  USER: "root"
  PASSWORD: "123456"
  DATABASE: "catarc"
  MAX_CONNECTIONS: 17
  TIMEOUT: 5

MONGO:
  HOST: "192.168.10.187"
  PORT: 27017
  AUTH_DB: "admin"
  USER: "root"
  PASSWORD: "123456"

REDIS:
  ADDRESS: 'redis://192.168.10.187:6379'
  HOST: "192.168.10.187"
  PORT: 6379
  DB: 15
  ENCODING: "utf-8"
  PASSWORD:
  MAXSIZE: 16
  TIMEOUT: 3

CELERY_REDIS:
  ADDRESS: ''
  HOST: ""
  PORT: 6379
  DB: 7
  ENCODING: "utf-8"
  PASSWORD:
  MAXSIZE: 16
  TIMEOUT: 3

CEILOMETER:
  HOST: ""
  SERVICE: ""

EPC:
  BASE_CAR_HOST: ''

TEST_ENV: 'DEV'

EMAIL:
  HOSTNAME: "smtp.exmail.qq.com"
  PORT: 465
  USERNAME: ""
  PASSWORD: ""

